/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fix_care.form;

import fix_care.clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class Alta_Edificio extends javax.swing.JPanel {

    /**
     * Creates new form Alta_Edificio
     */
    public Alta_Edificio() {
        initComponents();
    }

      private void guardarDepartamento() {
    String encargadoSeleccionado = (String) cmbEncargado.getSelectedItem();
        String departamentoTexto = txtEdificio.getText().trim();
        
        // Validar que se haya seleccionado un encargado y se haya escrito un nombre de departamento
        if (encargadoSeleccionado == null || encargadoSeleccionado.isEmpty() || departamentoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un encargado y escriba el nombre del departamento.", "Error de validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extraer el ID del encargado del string seleccionado en el JComboBox
        int idEncargado = Integer.parseInt(encargadoSeleccionado.split(" - ")[0]);

        Connection conn = null;
        try {
            // Creamos una instancia de tu clase de conexión
            ConexionBD objConexion = new ConexionBD();
            // Llamamos al método de instancia para obtener la conexión
            conn = objConexion.conexionDataBase();

            if (conn != null) {
                String sql = "INSERT INTO departamento (idUsuario, nombreDepartamento) VALUES (?, ?)";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setInt(1, idEncargado);
                    stmt.setString(2, departamentoTexto);
                    stmt.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this, "Departamento registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Limpiar los campos después de guardar
                    txtEdificio.setText("");
                    // No necesitas cmbEncargado.setSelectedIndex(0) porque el formulario se recarga en el constructor.
                }
            } else {
                 JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión a la base de datos.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el departamento: " + e.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Aseguramos que la conexión se cierre al final
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    System.err.println("Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEncargado = new javax.swing.JLabel();
        cmbEncargado = new javax.swing.JComboBox<>();
        labelEdificio = new javax.swing.JLabel();
        txtEdificio = new javax.swing.JTextField();
        loginBtn = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelEncargado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEncargado.setForeground(new java.awt.Color(102, 102, 102));
        labelEncargado.setText("Encargado:");

        cmbEncargado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEncargado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEncargadoActionPerformed(evt);
            }
        });

        labelEdificio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdificio.setText("Edificio:");

        txtEdificio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdificioActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(8, 55, 116));

        btnGuardar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEncargado)
                    .addComponent(labelEdificio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEncargadoActionPerformed

    private void txtEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdificioActionPerformed
        if (txtEdificio.getText().equals("Ingresa el edificio y su letra")) {
            txtEdificio.setText("");
            txtEdificio.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEdificioActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        guardarDepartamento();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        loginBtn.setBackground(new Color(33,161,153));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        loginBtn.setBackground(new Color(8, 55, 116));
    }//GEN-LAST:event_btnGuardarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cmbEncargado;
    private javax.swing.JLabel labelEdificio;
    private javax.swing.JLabel labelEncargado;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JTextField txtEdificio;
    // End of variables declaration//GEN-END:variables
}
